services:
  - type: web
    name: jt-express-chat-mvp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: SQLITE_PATH
        value: /var/data/app.db
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
